{
	imports = [
		./git.nix
    ./qt.nix
    ./cava.nix
    ./sway/swaync/swaync.nix
    ./starship.nix
    ./gtk.nix
    ./cursor.nix
    ./kitty.nix
    ./wm/waybar.nix
    ./wm/hypr
    ./rofi/rofi.nix
    ./fastfetch.nix
    ./spicetify.nix
    ./wlogout/wlogout.nix
    ./pywal
	];
}
